name: ci

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Upgrade pip version
        run: pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check black formatter
        run: black . --check --diff
